baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "Matt Jones Technology"
theme = "hugo-profile"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]



[services]
#  [services.googleAnalytics]
#    id = "G-MEASUREMENT_ID"
#  [services.disqus]
#    shortname = "your-disqus-shortname"

[pagination]
  pagerSize = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "Blog posts"
    url = "/blogs"
    weight = 1
  

[params]
  title = "Matt Jones Technology"
  description = "Text about my cool site"
  favicon = "/images/logo.svg"
  useBootstrapCDN = false
  mathjax = false
  animate = true

  [params.theme]
    # disableThemeToggle = true
    # defaultTheme = "light" # dark

  [params.font]
    fontSize = "1rem"
    fontWeight = 400
    lineHeight = 1.5
    textAlign = "left"

  [params.navbar]
    align = "ms-auto"
    brandName = "Matt Jones Technology"
    disableSearch = false
    [params.navbar.stickyNavBar]
      enable = true
      showOnScrollUp = true
    enableSeparator = false
    [params.navbar.menus]
      disableAbout = false
      disableExperience = false
      disableEducation = false
      disableProjects = false
      disableAchievements = false
      disableContact = false

  [params.hero]
    enable = true
    intro = "Hi, my name is"
    title = "Matt."
    subtitle = "I build enterprise architecture teams"
    content = "I build enterprise architecture teams that break down silos and bridge the gap between business and technology. My passion is helping organizations align strategy with execution, delivering solutions that are both practical and future-ready."
    image = "/images/hero.svg"
    [params.hero.bottomImage]
      enable = true
    [params.hero.button]
      enable = true
      name = "Resume"
      url = "#"
      download = true
      newPage = false
    [params.hero.socialLinks]
      [[params.hero.socialLinks.fontAwesomeIcons]]
        icon = "fab fa-github"
        url = "https://github.com/mattjonesorg"
      [[params.hero.socialLinks.fontAwesomeIcons]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/mattjonestechnology/"
      [[params.hero.socialLinks.fontAwesomeIcons]]
        icon = "fab fa-facebook"
        url = "https://www.facebook.com/mattjones.org/"
      [[params.hero.socialLinks.customIcons]]
        icon = "/images/logo.svg"
        url = "https://mattjones.technology/"

  [params.about]
    enable = true
    title = "About Me"
    image = "/images/me.png"
    content = """Great architecture starts with great conversations. I use techniques like Event Storming to get business and technology teams in the same room—mapping out processes, uncovering hidden complexities, and building a shared understanding before a single line of code is written. This collaborative approach eliminates confusion early, reduces rework, and sets projects on a path to success.

Beyond individual projects, I help organizations establish a clear technology strategy that stays aligned with business goals. Whether it’s modernizing legacy systems, adopting cloud services, or streamlining operations, my focus is always the same: making sure the technology serves the business—not the other way around.

Good architecture isn’t just about diagrams—it’s about building a foundation where teams can move faster, with less friction, and deliver real business value."""
    [params.about.skills]
      enable = false
      title = "Here are a few technologies I've been working with recently:"
      items = ["HTML", "CSS", "JavaScript", "React", "Node", "Express"]

  [params.experience]
    enable = true

  [params.education]
    enable = true
    title = "Education and Awards"

  [params.achievements]
    enable = true
    [[params.achievements.items]]
      title = "Google kickstart runner"
      content = "I solved all problems with optimal solution."
      url = "https://example.com"
      image = "/images/achievement.jpg"
    [[params.achievements.items]]
      title = "Facebook Hackathon Winner"
      content = "Developed a product using Artificial Intelligence."
      image = "/images/achievement.jpg"
    [[params.achievements.items]]
      title = "Hugo Profile"
      content = "Developed a theme and getting 1K+ downloads per month."
      url = "https://github.com/gurusabarish/hugo-profile"
      image = "/images/achievement.jpg"
    [[params.achievements.items]]
      title = "Microsoft Imagine Runner"
      content = "We are developed a product which can help others."
    [[params.achievements.items]]
      title = "Google Summer of Code"
      content = "Contributed to a open source project."
      url = "https://example.com"

  [params.projects]
    enable = false
    [[params.projects.items]]
      title = "Hugo Profile"
      content = "A highly customizable and mobile first Hugo template for personal portfolio and blog."
      image = "/images/projects/profile.png"
      featured = { name = "Demo", link = "https://hugo-profile.netlify.app" }
      badges = ["Hugo", "Bootstrap", "Javascript"]
      links = [
        { icon = "fa fa-envelope", url = "mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f" },
        { icon = "fab fa-github", url = "https://github.com/gurusabarish/hugo-profile" },
        { icon = "fab fa-twitter", url = "https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile" }
      ]
    [[params.projects.items]]
      title = "Image Converter"
      content = "A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django."
      image = "/images/projects/converter.jpg"
      featured = { name = "Demo", link = "https://django-converter.herokuapp.com" }
      badges = ["Django", "Bootstrap"]
      links = [
        { icon = "fab fa-github", url = "https://github.com/gurusabarish/converter" }
      ]
    [[params.projects.items]]
      title = "Hugo Profile V2"
      content = "A clean and simple Hugo template for personal portfolio and blog."
      image = "/images/projects/profile2.jpg"
      featured = { name = "Demo V2", link = "https://hugo-profile-2.netlify.app" }
      badges = ["Hugo", "Bootstrap", "Javascript"]
      links = [
        { icon = "fab fa-github", url = "https://github.com/gurusabarish/HugoProfileV2" }
      ]

  [params.contact]
    enable = true
    content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
    btnName = "Mail me"
    [params.contact.formspree]
      enable = true
      formId = "xanbjvvk"

  [params.footer]
    [params.footer.recentPosts]
      path = "blogs"
      count = 3
      title = "Recent Posts"
      enable = true
      disableFeaturedImage = false
    [params.footer.socialNetworks]
      github = "https://github.com"
      linkedin = "https://linkedin.com"
      twitter = "https://twitter.com"
      instagram = "https://instagram.com"
      facebook = "https://facebook.com"

  [params.listPages]
    disableFeaturedImage = false

  [params.singlePages]
    socialShare = true
    readTime = { enable = true, content = "min read" }
    scrollprogress = { enable = true }
    tags = { openInNewTab = true }

  [params.terms]
    read = "Read"
    toc = "Table Of Contents"
    copyright = "All rights reserved"
    pageNotFound = "Page not found"
    emailText = "Check out this site"

  [params.datesFormat]
    article = "Jan 2, 2006"
    articleList = "Jan 2, 2006"
    articleRecent = "Jan 2, 2006"
